;; See ../CONTRIBUTING.md for details.
((auto-mode-alist . (("\\.h\\'" . c++-mode)))
 (c++-mode . ((c-file-style . "linux")
              (indent-tabs-mode . t)
              (tab-width . 4)
              (c-basic-offset . 4)
              (c-file-offsets
               (arglist-cont . 0)
               (arglist-intro . +)
               (block-close . 0)
               (brace-entry-open . 0)
               (brace-list-close . 0)
               (brace-list-entry . 0)
               (brace-list-intro . +)
               (class-close . 0)
               (class-open . 0)
               (case-label . 0)
               (defun-block-intro . +)
               (defun-close . 0)
               (defun-open . 0)
               (else-clause . 0)
               (inclass . +)
               (inline-close . 0)
               (inline-open . 0)
               (label . 0)
               (member-init-cont . -)
               (member-init-intro . +)
               (statement . 0)
               (statement-block-intro . +)
               (statement-case-intro . +)
               (statement-cont . +)
               (substatement-open . 0)
               (topmost-intro . 0)))))
